on: 
  - push
  - pull_request
  - workflow_dispatch

name: Unit test
jobs:
  test:
    strategy:
      matrix:
        package: 
          # - ./bfsDfs
          # - ./concatenate
          # - ./reformat
          # - ./substring
          - ./... --ignore=./substring ./reformat 
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Smoke test
      run: | 
        go test ./... -v
